networks:
  default:
    name: docker-default-network
    external: true

include:
  - ../../docker-compose-build.yml

services:

  artemis:
    scale: 2
    image: quay.io/artemiscloud/activemq-artemis-broker
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      AMQ_CLUSTERED: true

  producer:
    image: artemis-quick/producer:1.0-${QUARKUS_MODE:-jvm}
    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 61616
    ports:
      - "8080:8080"

  processor:
    image: artemis-quick/processor:1.0-${QUARKUS_MODE:-jvm}
    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 61616

