networks:
  default:
    name: docker-default-network
    external: true

include:
  - ../../docker-compose-build.yml

services:

  artemis:
    scale: 1
    image: quay.io/artemiscloud/activemq-artemis-broker
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      AMQ_CLUSTERED: true

  artemis-ports:
    image: quay.io/artemiscloud/activemq-artemis-broker
    environment:
      AMQ_USER: quarkus
      AMQ_PASSWORD: quarkus
      AMQ_CLUSTERED: true
      AMQ_EXTRA_ARGS: "--relax-jolokia"
    ports:
      - "8161:8161"
      - "61616:61616"
      - "5672:5672"

  producer:
    image: artemis-quick/producer:1.0-${QUARKUS_MODE:-jvm}
    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 61616
    ports:
      - "8080:8080"

  processor:
    image: artemis-quick/processor:1.0-${QUARKUS_MODE:-jvm}
    environment:
      AMQP_HOST: artemis
      AMQP_PORT: 61616

