networks:
  default:
    name: docker-default-network
    external: true

services:

  artemis:
    image: avogt/traefik-with-localhost-tls:2.10
    #image: traefik
    ports:
      - '8888:8080'
      - '61616:61616'
    command:
      - --entryPoints.artemis.address=:61616
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.exposedbydefault=false
      - --api
      - --api.insecure=true
      - --api.dashboard=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
