FROM quay.io/artemiscloud/activemq-artemis-broker:latest


# COPY broker-base.xml /home/jboss/broker/etc/broker.xml
 #COPY broker-base.xml /var/lib/artemis-instance/etc-override
ENV AMQ_CLUSTERED  true